"""Shared deck I/O for the tools. Not runnable on its own.

Both audio.py and images.py load the same two files and write the same
attribution list, so that lives here rather than drifting between them.
"""
import json, re, urllib.error, urllib.parse, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NOTES_PATH = ROOT / "deck/notes.json"
MANIFEST_PATH = ROOT / "media/manifest.json"
ATTRIB_PATH = ROOT / "media/ATTRIBUTION.md"

KEY_ORDER = ["id", "word", "article", "gloss", "pos", "ipa", "note", "image", "image_alt",
             "image_basis", "image_prompt", "audio", "sentence", "cards", "reviewed"]
SENT_KEY_ORDER = ["nl", "en", "gap", "answer", "answer_lemma", "audio"]

# Everything the project puts where Windows can open it goes under one root.
OUT_ROOT = "nlcards"


def out_dir(sub):
    for d in sorted(Path("/mnt/c/Users").glob("*/Downloads")):
        if d.is_dir() and not d.parent.name.startswith(("Default", "All Users", "Public")):
            return d / OUT_ROOT / sub
    return ROOT / ".out" / sub          # gitignored fallback when not on WSL


def load_key(name):
    """Read one key out of .env. Never printed, never committed."""
    env = ROOT / ".env"
    if not env.exists():
        raise SystemExit(f"no .env — expected {name} in {env}")
    for line in env.read_text(encoding="utf-8").splitlines():
        if line.strip().startswith(f"{name}="):
            v = line.split("=", 1)[1].strip().strip("'\"")
            if v:
                return v
    raise SystemExit(f".env has no {name} value")


def esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def reorder(d, order):
    return {k: d[k] for k in order if k in d} | {k: v for k, v in d.items() if k not in order}


def load():
    deck = json.loads(NOTES_PATH.read_text(encoding="utf-8"))
    manifest = (json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
                if MANIFEST_PATH.exists() else {})
    return deck, deck["notes"], manifest


def save(deck, notes, manifest):
    deck["notes"] = [
        reorder({**n, **({"sentence": reorder(n["sentence"], SENT_KEY_ORDER)}
                         if isinstance(n.get("sentence"), dict) else {})}, KEY_ORDER)
        for n in notes]
    NOTES_PATH.write_text(json.dumps(deck, ensure_ascii=False, indent=2) + "\n",
                          encoding="utf-8")
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(manifest, ensure_ascii=False, indent=2,
                                        sort_keys=True) + "\n", encoding="utf-8")
    write_attribution(manifest)


def write_attribution(manifest):
    """Reused media carries licence obligations; meet them from the manifest."""
    rows = [(rel, v) for rel, v in sorted(manifest.items())
            if v.get("source") in ("commons", "openverse", "wikipedia")]
    if not rows:
        ATTRIB_PATH.unlink(missing_ok=True)
        return
    lines = ["# Media attribution", "",
             "Reused under the licences below. Generated by the tools in `tools/` —",
             "do not edit by hand.", "",
             "| File | Title | Author | Licence | Source |", "| --- | --- | --- | --- | --- |"]
    for rel, v in rows:
        page = v.get("page") or v.get("source_url") or ""
        title = v.get("commons_file") or v.get("title") or ""
        link = f"[{title}]({page})" if page else title
        lines.append(f"| `{rel}` | {link} | {v.get('author', 'unknown')} "
                     f"| {v.get('licence', 'unknown')} | {v.get('source')} |")
    ATTRIB_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ── Firestore ──────────────────────────────────────────────────────────
# This deck shares a Firebase project and a collection (`progress`) with the
# Polish trainer, whose documents belong to a real student. Every tool that
# touches Firestore therefore resolves its document through deck_id() below,
# which only ever returns an id with the "nl-" prefix the app mints. A tool
# that took a bare --user and defaulted to something would be one typo away
# from writing to someone else's progress.
PROJECT = "flashcards-f5b40"
FS_BASE = (f"https://firestore.googleapis.com/v1/projects/{PROJECT}"
           f"/databases/(default)/documents/progress")
UID_PREFIX = "nl-"


def web_key():
    """The Firebase web key, read out of index.html. Not a secret."""
    m = re.search(r'apiKey:\s*"([^"]+)"', (ROOT / "index.html").read_text(encoding="utf-8"))
    if not m:
        raise SystemExit("could not find the Firebase apiKey in index.html")
    return m.group(1)


def deck_id(explicit=""):
    """The one document id this repo's tools may touch.

    An explicit id must carry the prefix. Otherwise NL_UID from .env, and
    failing that the only nl- document in the collection. Refuses rather than
    guesses when there are several."""
    if explicit:
        if not explicit.startswith(UID_PREFIX):
            raise SystemExit(f"refusing {explicit!r}: not an {UID_PREFIX} deck — the "
                             f"other documents in this collection are the Polish app's")
        return explicit
    env = ROOT / ".env"
    if env.exists():
        for line in env.read_text(encoding="utf-8").splitlines():
            if line.strip().startswith("NL_UID="):
                v = line.split("=", 1)[1].strip().strip("'\"")
                if v:
                    return deck_id(v)
    url = f"{FS_BASE}?key={web_key()}&mask.fieldPaths=updated&pageSize=300"
    try:
        with urllib.request.urlopen(url, timeout=30) as r:
            docs = json.load(r).get("documents", [])
    except urllib.error.URLError as e:
        raise SystemExit(f"could not list decks: {e}")
    ids = [d["name"].rsplit("/", 1)[-1] for d in docs]
    mine = [i for i in ids if i.startswith(UID_PREFIX)]
    if not mine:
        raise SystemExit("no nl- deck in Firestore yet — open the app and review "
                         "something first, or set NL_UID in .env")
    if len(mine) > 1:
        raise SystemExit(f"{len(mine)} nl- decks exist ({', '.join(mine)}); "
                         f"set NL_UID in .env or pass --user")
    return mine[0]
